controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    fishbot_joint_state_broadcaster:
        #JointStateBroadcaster 是一个用于发布机器人关节状态的节点，(控制器节点)
        #通常这个节点会订阅包含关节位置、速度和加速度等信息的主题，并将这些信息整合后发布到 /joint_states 主题上。
        #之后robot_state_publisher会将该话题的数据转换成TF数据并发布
        type: joint_state_broadcaster/JointStateBroadcaster
    fishbot_effort_controller:
        type: effort_controllers/JointGroupEffortController
    fishbot_diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

fishbot_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

fishbot_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.20
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.032

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.3
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10